apiVersion: apps/v1
kind: Deployment
metadata:
  name: deytongarcia-deployment
  namespace: deytongarcia-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-container
        image: deytongarcia10/deytongarciaavalos:latest
        ports:
        - containerPort: 8087
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"